version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg_promad
    restart: always
    environment:
      POSTGRES_USER: promad
      POSTGRES_PASSWORD: promad_password
      POSTGRES_DB: clientes
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
